## Importing PyTorch

Note: Before running any of the code in this notebook, you should have gone through the [PyTorch setup steps](https://pytorch.org/get-started/locally/).

However, if you're running on Google Colab, everything should work (Google Colab comes with PyTorch and other libraries installed).

In [1]:
# Import PyTorch
import torch
# Check version
print(torch.__version__)

1.12.1+cu113


In [2]:
# Get Infos on the GPU installed.
!nvidia-smi

Thu Nov 10 15:34:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

Now that we've got PyTorch imported, it's time to learn about tensors.

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

### Creating tensors

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [2]:
# Sclar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Check the dimension of a tensor
scalar.ndim

0

In [5]:
# Get tensor get back as Python int
scalar.item()

7

A vector is a single dimension tensor but can contain many numbers.

In [4]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim # number of pairs square brackets

1

In [6]:
vector.shape # how the elements inside are arranged

torch.Size([2])

MATRIX has two dimensions.

In [7]:
# Matrix
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([1, 2])

Tensor is an n-dimensional array of numbers.

In [10]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([2, 3, 3])

Note: You might've noticed that we use lowercase letters for scalar and vector and uppercase letters for MATRIX and TENSOR. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W.

### Random tensors

In [13]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3384, 0.3180, 0.2915, 0.5756],
        [0.7400, 0.0585, 0.4237, 0.2367],
        [0.7088, 0.7066, 0.4750, 0.9311]])

In [14]:
random_tensor.ndim

2

In [15]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.9626, 0.5328, 0.5518,  ..., 0.5964, 0.5997, 0.5206],
         [0.8501, 0.8908, 0.7927,  ..., 0.1356, 0.3592, 0.2818],
         [0.0689, 0.7688, 0.8507,  ..., 0.1299, 0.5668, 0.3313],
         ...,
         [0.6603, 0.7782, 0.8204,  ..., 0.3944, 0.9583, 0.3095],
         [0.5835, 0.5440, 0.5062,  ..., 0.8947, 0.8118, 0.1687],
         [0.1897, 0.4670, 0.0431,  ..., 0.0975, 0.0518, 0.2779]],

        [[0.4090, 0.8434, 0.6432,  ..., 0.4132, 0.0184, 0.8873],
         [0.2262, 0.5539, 0.5239,  ..., 0.0051, 0.6426, 0.5905],
         [0.8637, 0.2044, 0.6112,  ..., 0.3858, 0.8013, 0.5192],
         ...,
         [0.4751, 0.3867, 0.3462,  ..., 0.5472, 0.2827, 0.9339],
         [0.5070, 0.7013, 0.8827,  ..., 0.3545, 0.8653, 0.7603],
         [0.2617, 0.2384, 0.1280,  ..., 0.1131, 0.9545, 0.2143]],

        [[0.0464, 0.6839, 0.0259,  ..., 0.6498, 0.7901, 0.2180],
         [0.4043, 0.3934, 0.6355,  ..., 0.8136, 0.5752, 0.8014],
         [0.5113, 0.9628, 0.8889,  ..., 0.3310, 0.1743, 0.

## Zeros and ones

In [16]:
# Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

## Create a range of tensors and tensors-like 

In [19]:
# use torch.range() // torch.arange()
one_to_ten = torch.range(start=0, end=10, step=1)
one_to_ten

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
# Creating tensors like (to get a tensor of a certain type with the same shape as another tensor)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types)

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as **32-bit floating point.**

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

The reason for all of these is to do with **precision in computing.**

Precision is the amount of detail used to describe a number (the more detail you have to calculate on, the more compute you have to use.).

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).




In [22]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data type (eg: torch.float16, torch.float32, torch.float64, torch.int32, torch.int64)
                               device=None, # "cpu" or "cuda"
                               requires_grad=False) # # if True, operations perfromed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half would also work
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Getting information from tensors

The most common attributes you'll want to find out about tensors are:

`shape` - what shape is the tensor? (some operations require specific shape rules)

`dtype` - what datatype are the elements within the tensor stored in?

`device` - what device is the tensor stored on? (usually GPU or CPU)

In [25]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0211, 0.5855, 0.9450, 0.6823],
        [0.4901, 0.7889, 0.4776, 0.2716],
        [0.3955, 0.4508, 0.6539, 0.6403]])

In [26]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0211, 0.5855, 0.9450, 0.6823],
        [0.4901, 0.7889, 0.4776, 0.2716],
        [0.3955, 0.4508, 0.6539, 0.6403]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)
- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [27]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [31]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10) # torch.multiply() also works

tensor([10, 20, 30])

In [32]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [torch.matmul()](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

1- Element-wise multiplication

2- Matrix multiplication (dot product)

In [33]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [35]:
# Shapes for matrix multiplication
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])
# torch.mm is the same as torch.matmul
torch.matmul(tensorA, tensorB)

RuntimeError: ignored

In [36]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.
A **transpose** switches the axes of dimensions of a given tensor.

In [37]:
tensorB, tensorB.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]), torch.Size([3, 2]))

In [38]:
tensorB.T, tensorB.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]), torch.Size([2, 3]))

In [39]:
torch.matmul(tensorA, tensorB.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [40]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [42]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [43]:
# Find the mean
# torch.mean() function requires a tensor of float32, otherwise the operation will fail
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

## Finding the positional min and max

You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [44]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# Find the position in tensor that has the minimum value with argmin() -> return the index
x.argmin()

tensor(0)

In [46]:
x[0]

tensor(0)

In [47]:
# Find the position in tensor that has the maximun value with argmin() -> return the index
x.argmax()

tensor(9)

In [48]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:
* Reshaping -> reshapes an input tensor to a defined shape
* View -> Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking -> combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -> removes all '1' dimensions from a tensor.H
* Unsqueeze -> ass a '1' dimension to a target tensor
* Permute -> Return a view of the input with dimension permuted (swapped) in a certain way.

In [52]:
# Create a tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [53]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [54]:
# Change the view ( a view share the memory with the original tensor)
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [56]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [57]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # Stack  vertically
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [58]:
x_stacked = torch.stack([x, x, x, x], dim=1) # Stack  horizontally
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [59]:
# torch.squeeze() - removes all single (1) dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [60]:
x_squeeze = x_reshaped.squeeze()
x_squeeze

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
x_squeeze.shape

torch.Size([10])

In [62]:
# torch.unsqueeze() - adds a single dimension to a target at a specific  dim (dimension)
x_unsqueezed = x_squeeze.unsqueeze(dim=1) # add on the first dimension
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]), torch.Size([10, 1]))

In [63]:
# torch.permute -> rearrange the dimensions of a target in a specified order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, coulour_channels)

# Permute the original tensor to reaarange the axis (or dim) order (NB: a permute is a view)
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [64]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(0.1833), tensor(0.1833))

In [65]:
x_original[0, 0, 0] = 0.2

In [ ]:
x_permuted[0, 0, 0]

tensor(0.2000)

## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.
### Indexing in Pytorch is similar to indexing with numpy

In [71]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [73]:
# Let's index on the first bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [75]:
# Let's index on the inner bracket (last dimmension)
x[0][0][0]

tensor(1)

In [70]:
# We can also use ":" to select "all" of a target dimension
x[:, 0], x[:, 1], x[:, 2]

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

In [77]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension.
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension.
x[:, 1, 1]

tensor([5])

In [78]:
# Get index 0 of 0th and 1st dimension and all value of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [79]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [80]:
# Index on x to return 3, 6, 9
x[0][:, 2]

tensor([3, 6, 9])

## Pytorch tensors and Numpy
Numpy is a popular scientific Python numerical computing library.

An because of this, Pytorch has functionality to interact with it.
* Data in Numpy, want it Pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy : `torch.Tensor.numpy()`

In [81]:
# Numpy array to tensor
import numpy as np
array = np.arange(1., 10.)
tensor = torch.from_numpy(array).type(torch.float32) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype flot64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [82]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [83]:
# Change the value of array, what will this do to 'tensor' ?
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happen to 'numpy_tensor' ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In [85]:
# Create two random tensors
random_tensorA = torch.rand(3, 4)
random_tensorB = torch.rand(3, 4)
print(random_tensorA == random_tensorB)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [86]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # Only work for one block of code
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations) 
GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware +  Pytorch working behind the scenes to make everything hunky dory (good).

### 1. Getting the GPU

1. Easiest - Use google colab for a free GPU
2. Use your own GPU - take a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options.
3. Use cloud computing (GCP, AWS, Azure). 

In [ ]:
# Check if you've got access to a Nvidia GPU
!nvidia-smi

Fri Oct 14 05:48:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with Pytorch

In [ ]:
torch.cuda.is_available() # cuda allow us to use gpu for numerical computing.

True

In [ ]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices (GPU) PyTorch has access to using
torch.cuda.device_count()

1

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU, we can't transform it to numpy because numpy objects only work on CPU.
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it on CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])